name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 添加權限設定
permissions:
  contents: read
  pages: write
  id-token: write

# 允許並發部署
concurrency:
  group: "pages"
  cancel-in-progress: false

# 環境變數
env:
  NODE_VERSION: '20.18.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Pre-deployment checks
      run: npm run pre-deploy
      
    - name: Build application
      run: npx nuxt build --preset github_pages

    - name: Ensure .nojekyll exists
      run: touch ./.output/public/.nojekyll
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./.output/public
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Post-deployment validation
      run: npm run post-deploy 